# Generated by Django 5.2.3 on 2025-06-26 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seguridadApp', '0001_initial'),
        ('ventasApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeracion', models.CharField(max_length=15)),
                ('serie', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CabeceraVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaventa', models.DateField()),
                ('estado', models.CharField(max_length=11)),
                ('total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('nrodoc', models.CharField(max_length=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=20)),
                ('igv', models.DecimalField(decimal_places=2, max_digits=20)),
                ('idcliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridadApp.cliente')),
                ('idtipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas2App.tipo')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cantidad', models.IntegerField()),
                ('cabecera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas2App.cabeceraventa')),
                ('idproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventasApp.productos')),
            ],
        ),
    ]
