# Generated by Django 5.2.3 on 2025-06-26 04:46

from django.db import migrations

def insertar_datos(apps, schema_editor):
    Tipo = apps.get_model('ventas2App', 'Tipo')
    Parametro = apps.get_model('ventas2App', 'Parametro')

    # Inserta valores predeterminados
    Tipo.objects.create(descripcion='FACTURA')
    Tipo.objects.create(descripcion='BOLETA')

    Parametro.objects.create(numeracion='00010', serie='001')
    Parametro.objects.create(numeracion='01000', serie='002')

class Migration(migrations.Migration):

    dependencies = [
        ('ventas2App', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insertar_datos),
    ]
